# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxnVhRsJ35GJcVP9sqxmRh5TvF392b9K
"""

!pip install -q gpt-2-simple
import gpt_2_simple as gpt2
sess = gpt2.start_tf_sess()
#upload checkpoint to /content/checkpoint/run1
gpt2.generate(sess, run_name='run1')